### ISSUE TITLE
Support for Windows and macOS ?

### ISSUE THREAD

**Issue by alx-xlx** [AdguardTeam/AdGuardVPNCLI#16] opened 2024-05-01 03:56 UTC
### Please answer the following questions for yourself before submitting a question.

- [ ] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

should I be expecting CLI for windows and macOS as well ?

**Comment by sfionov** [comment] 2024-05-01 07:23
Duplicate of #17

**Closed by sfionov** 2024-05-01 07:23 UTC
Labels: Priority: P4
